import { createEmployee, updateEmployee, updateEmployeeStatus } from "@/app/actions";
import { db } from "@/lib/db";
import { money } from "@/lib/format";
import { requirePageRoles } from "@/lib/security";

type Employee={id:string;employee_no:string;full_name:string;department_id:string;department:string;job_title:string;employment_type:string;employment_status:string;date_joined:string;basic_salary:number;bank_name:string|null;account_name:string|null;account_number:string|null;ssnit_number:string|null;tax_id:string|null};
type Department={id:string;name:string};
const STATUSES=["Active","Suspended","On Leave","Terminated","Resigned","Retired","Deceased"] as const;
const TYPES=["Permanent","Fixed Term","Contract","Casual","Temporary","Apprentice"] as const;

export default async function EmployeesPage(){
  await requirePageRoles("HR / Administrator","System Administrator");const sql=db();
  const [employeeRows,departmentRows]=await Promise.all([
    sql`SELECT e.id,e.employee_no,e.full_name,e.department_id,d.name department,e.job_title,e.employment_type,e.employment_status,e.date_joined,e.basic_salary::float,e.bank_name,e.account_name,e.account_number,e.ssnit_number,e.tax_id FROM employees e JOIN departments d ON d.id=e.department_id ORDER BY e.full_name`,
    sql`SELECT id,name FROM departments WHERE active ORDER BY name`,
  ]);
  const employees=employeeRows as Employee[],departments=departmentRows as Department[];const active=employees.filter(e=>e.employment_status==="Active").length;
  return <><div className="page-head"><div><span className="eyebrow">Controlled master data</span><h1>Employees</h1><p>{employees.length} persistent records · {active} active for future payroll periods.</p></div></div>
    <details className="card form-card"><summary>+ Add employee</summary><form action={createEmployee} className="form-grid"><EmployeeFields departments={departments}/><div className="form-actions"><button className="button primary">Create employee</button></div></form></details>
    <section className="card"><div className="table-wrap"><table><thead><tr><th>Employee</th><th>Department</th><th>Employment</th><th>Basic salary</th><th>Records</th><th>Status</th><th>Actions</th></tr></thead><tbody>{employees.map(e=><tr key={e.id}><td><b>{e.full_name}</b><small>{e.employee_no} · {e.job_title}</small></td><td>{e.department}</td><td>{e.employment_type}</td><td className="money">{money(e.basic_salary)}</td><td><span className={`badge ${e.bank_name&&e.account_name&&e.account_number&&e.ssnit_number?"green":"red"}`}>{e.bank_name&&e.account_name&&e.account_number&&e.ssnit_number?"Complete":"Missing data"}</span></td><td><span className={`badge ${tone(e.employment_status)}`}>{e.employment_status}</span></td><td><details className="row-editor"><summary>Edit details</summary><form action={updateEmployee}><input type="hidden" name="employeeId" value={e.id}/><input type="hidden" name="employeeNo" value={e.employee_no}/><EmployeeFields departments={departments} employee={e}/><label>Change effective date<input name="effectiveDate" type="date" required/></label><label>Reason<input name="reason" minLength={5} maxLength={500} required/></label><label>Confirm employee number<input name="confirmation" autoComplete="off" placeholder={e.employee_no} required/></label><button className="button primary">Save audited changes</button></form></details><details className="row-editor"><summary>Manage status</summary><form action={updateEmployeeStatus}><input type="hidden" name="employeeId" value={e.id}/><input type="hidden" name="employeeNo" value={e.employee_no}/><label>New status<select name="status" defaultValue={e.employment_status==="Active"?"Suspended":"Active"}>{STATUSES.filter(status=>status!==e.employment_status).map(status=><option key={status}>{status}</option>)}</select></label><label>Reason<input name="reason" minLength={5} maxLength={500} required/></label><label>Confirm employee number<input name="confirmation" autoComplete="off" placeholder={e.employee_no} required/></label><small>Historical payroll records remain unchanged.</small><button className="button primary">Update status</button></form></details></td></tr>)}</tbody></table></div></section>
  </>;
}

function EmployeeFields({departments,employee}:{departments:Department[];employee?:Employee}){return <><label>Full name<input name="fullName" defaultValue={employee?.full_name} required/></label>{!employee?<label>Employee number<input name="employeeNo" placeholder="CPL-007" required/></label>:null}<label>Department<select name="departmentId" defaultValue={employee?.department_id} required>{departments.map(d=><option value={d.id} key={d.id}>{d.name}</option>)}</select></label><label>Job title<input name="jobTitle" defaultValue={employee?.job_title} required/></label><label>Employment type<select name="employmentType" defaultValue={employee?.employment_type||"Permanent"}>{TYPES.map(type=><option key={type}>{type}</option>)}</select></label><label>Date joined<input name="dateJoined" type="date" defaultValue={employee?.date_joined} required/></label><label>Basic monthly salary<input name="basicSalary" type="number" min="0" step="0.01" defaultValue={employee?.basic_salary} required/></label><label>Bank name<input name="bankName" defaultValue={employee?.bank_name||""}/></label><label>Account name<input name="accountName" defaultValue={employee?.account_name||""}/></label><label>Account number<input name="accountNumber" defaultValue={employee?.account_number||""}/></label><label>SSNIT number<input name="ssnitNumber" defaultValue={employee?.ssnit_number||""}/></label>{employee?<label>Tax ID<input name="taxId" defaultValue={employee.tax_id||""}/></label>:null}</>}
function tone(status:string){if(status==="Active")return "green";if(status==="Suspended"||status==="On Leave")return "amber";return "red"}
