import { recordPayment, transitionPayroll } from "@/app/actions";
import { db } from "@/lib/db";
import { date, money } from "@/lib/format";
import { identity } from "@/lib/security";

type Period={id:string;period_code:string;status:string;stage:number;created_by_id:string|null;created_by_name:string;gross:number;net:number;paye:number;employee_pension:number;employer_pension:number;employees:number;pending_hod:number;locked_at:string|null};
type Event={id:string;action:string;from_status:string;to_status:string;actor_name:string;actor_role:string;comment:string|null;created_at:string};

export default async function ApprovalsPage(){const {profile}=await identity();const sql=db();const rows=await sql`SELECT p.id,p.period_code,p.status,p.stage,p.created_by_id,p.created_by_name,p.locked_at,count(pe.id)::int employees,count(*) FILTER(WHERE NOT pe.hod_verified)::int pending_hod,COALESCE(sum(pe.gross_pay),0)::float gross,COALESCE(sum(pe.net_pay),0)::float net,COALESCE(sum(pe.paye),0)::float paye,COALESCE(sum(pe.employee_pension),0)::float employee_pension,COALESCE(sum(pe.employer_pension),0)::float employer_pension FROM payroll_periods p LEFT JOIN payroll_entries pe ON pe.period_id=p.id GROUP BY p.id ORDER BY p.year DESC,p.month DESC LIMIT 1` as Period[];const p=rows[0];const events=p?await sql`SELECT id,action,from_status,to_status,actor_name,actor_role,comment,created_at FROM approval_events WHERE period_id=${p.id} ORDER BY created_at DESC` as Event[]:[];if(!p)return <div className="empty">No payroll is available for approval.</div>;const labels=["Prepare","HOD review","GM approval","CEO review","Payment","Locked"];return <><div className="page-head"><div><span className="eyebrow">Database-enforced workflow</span><h1>Payroll approvals</h1><p>The preparer cannot approve; every transition is validated and audited.</p></div><span className={`badge ${p.locked_at?"green":"blue"}`}>{p.status}</span></div><section className="card"><div className="card-head"><div><h2>{p.period_code}</h2><p>Prepared by {p.created_by_name}</p></div><ApprovalAction role={profile!.role} stage={p.stage} periodId={p.id}/></div><div className="stages">{labels.map((x,i)=><div className={`stage ${i<p.stage?"done":i===p.stage?"current":""}`} key={x}><i/>{x}</div>)}</div></section><section className="stats"><Stat label="Gross payroll" value={money(p.gross)}/><Stat label="Net payroll" value={money(p.net)}/><Stat label="Employees" value={String(p.employees)}/><Stat label="Pending HOD" value={String(p.pending_hod)}/></section><section className="grid two"><article className="card"><h2>Control checks</h2><Check label="Maker–checker validation" ok/><Check label="Negative net pay" ok/><Check label="Department verification" ok={p.pending_hod===0}/><Check label="Payroll locking" ok={Boolean(p.locked_at)}/><Check label="Payment separation" ok={p.stage>=4}/></article><article className="card"><h2>Approval history</h2>{events.length?events.map(e=><div className="timeline" key={e.id}><i/><div><b>{e.to_status}</b><p>{e.actor_name} · {e.actor_role}</p><small>{date(e.created_at)}{e.comment?` · ${e.comment}`:""}</small></div></div>):<p className="muted">No approval actions yet.</p>}</article></section></>}
function ApprovalAction({role,stage,periodId}:{role:string;stage:number;periodId:string}){let action="",label="";if(role==="Payroll Officer"&&stage===0){action="submit";label="Submit for HOD review"}if(role==="Head of Department"&&stage===1){action="hod_verify";label="Verify departments"}if(role==="General Manager"&&stage===2){action="gm_approve";label="Approve payroll"}if(role==="CEO"&&stage===3){action="ceo_approve";label="Approve escalation"}if(role==="Payment Officer"&&stage===4)return <form action={recordPayment} className="inline-form"><input type="hidden" name="periodId" value={periodId}/><input name="paymentReference" placeholder="Bank payment reference" required/><input name="comment" placeholder="Optional comment"/><button className="button primary">Record payment & lock</button></form>;if(!action)return <span className="info-box compact">Current stage belongs to another role.</span>;return <form action={transitionPayroll} className="inline-form"><input type="hidden" name="periodId" value={periodId}/><input type="hidden" name="action" value={action}/><input name="comment" placeholder="Approval comment"/><button className="button primary">{label}</button></form>}
function Stat({label,value}:{label:string;value:string}){return <article className="stat"><span>{label}</span><strong>{value}</strong></article>}
function Check({label,ok}:{label:string;ok:boolean}){return <div className="data-row"><span>{label}</span><span className={`badge ${ok?"green":"amber"}`}>{ok?"Passed":"Pending"}</span></div>}
